config/routes.rb
Rails.application.routes.draw do
  root "application#index"

  resources :campaigns, only:[:index, :create, :update]
  get '/user/:id/campaigns', to: 'campaigns#find_by_user', as: :user_campaigns
  get '/new_campaign', to: 'campaigns#new', as: :new_campaign
  get '/campaign/:id', to: 'campaigns#show', as: :campaign_details
  get '/campaign/:id/edit', to: 'campaigns#edit', as: :edit_campaign
  delete '/campaign/:id/delete_cover_image', to: 'campaigns#delete_cover_image', as: :delete_cover_image

  resources :contributions, only:[:index, :create]

  resources :deposits, only:[:index]

  resources :rewards, only:[:index]

  resources :sessions, only:[:create]
  get '/log_in', to: 'sessions#new', as: :log_in
  delete '/log_out', to: 'sessions#destroy', as: :log_out

  resources :users, only:[:index, :create, :update]
  get '/home', to: 'users#home', as: :home
  get '/profile/:id', to: 'users#show', as: :profile
  delete '/delete_profile', to: 'users#destroy', as: :delete_profile
  get '/sign_up', to: 'users#new', as: :sign_up
  get '/edit_profile', to: 'users#edit', as: :edit_profile
  delete '/delete_profile_image', to: 'users#delete_profile_image', as: :delete_profile_image

  resources :phones, only:[:create]
  delete '/profile/phones/:id/delete', to: 'phones#destroy', as: :delete_phone

  resources :cards, only:[:create, :update]
  get 'payment_methods/cards', to: 'cards#show', as: :payment_methods
  get 'payment_methods/manage', to: 'cards#manage', as: :manage_payment
  delete 'payment_methods/delete_card/:id', to: 'cards#destroy', as: :delete_card
end

app/models/user.rb
class User < ApplicationRecord
  # Profile image via ActiveStorage
  has_one_attached :profile_image

  # Sorcery gem:
  authenticates_with_sorcery!
  attr_accessor :skip_password

  # Validation:
  validates :password, length: {minimum: 8},
            if: -> {new_record? || changes[:crypted_password]},
            unless: :skip_password
  validates :password, confirmation: true,
            if: -> {new_record? || changes[:crypted_password]}
  validates :password_confirmation, presence: true,
            if: -> {new_record? || changes[:crypted_password]}
  validates :email, uniqueness: true


  # Relationships:
  belongs_to :user_role
  has_and_belongs_to_many :rewards, dependent: :delete_all
  has_many :cards, dependent: :delete_all
  has_many :campaigns
  has_many :contributions
  has_many :deposits, dependent: :delete_all
  has_many :phones, dependent: :delete_all

  # Methods:
  def amount_contributed
    amount = 0.00
    self.contributions.each do |donation|
      amount += donation.value
    end
    amount
  end

  def amount_received
    amount = 0.00
    self.campaigns.each do |campaign|
      amount += campaign.current_amount
    end
    amount
  end

  def count_contributions
    self.contributions.size
  end

  def count_campaigns
    self.campaigns.size
  end

  def join_date
    day = self.created_at.day.to_s
    mount = self.created_at.month.to_s
    year = self.created_at.year.to_s
    "#{day}/#{mount}/#{year}"
  end

  def update_date
    day = self.updated_at.day.to_s
    mount = self.updated_at.month.to_s
    year = self.updated_at.year.to_s
    "#{day}/#{mount}/#{year}"
  end

  def format_birth_date
    day = self.birth_date.day.to_s
    mount = self.birth_date.month.to_s
    year = self.birth_date.year.to_s
    "#{day}/#{mount}/#{year}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:index, :show, :new, :create]

  def index
    @users = User.all.page(params[:page])
  end

  def home
    @users = User.order(created_at: :desc).page(params[:users_page]).per(5)
    @campaigns = Campaign.order(created_at: :desc).page(params[:campaigns_page]).per(5)
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = current_user
    unless params[:profile_image].nil?
      @user.profile_image.destroy
      @user.profile_image.attach(params[:profile_image])
    end
    if @user.update_attributes(user_edit_params)
      flash[:success] = [["Alright!", "Your profile was updated"]]
      redirect_to profile_path(@user.id)
    else
      render 'edit'
    end
  end

  def edit
    @user = current_user
  end

  def create
    @user = User.new(user_create_params)
    @user.user_role_id = 2  # All users created don't have administrator
                            # privileges. They are normal users.
    @user.wallet_amount = 0.0 # All users start with empty wallet
    if @user.save
      flash.clear
      flash[:success] = [["", "User account successfully created!"]]
      redirect_to log_in_path
    else
      render 'new'
    end
  end

  def new
    @user = User.new
  end

  def destroy
    @user = current_user
    @user.destroy
    flash.clear
    flash[:info] = [["Goodbye!", "Your account has been deleted!"]]
    redirect_to root_path
  end

  def delete_profile_image
    @user = current_user
    @user.profile_image.destroy
    flash[:success] = [['All good!', 'Your profile image has been deleted']]
    redirect_to edit_profile_path
  end

  private
    def user_create_params
      params.require(:user).permit(:first_name, :last_name, :email, :password,
                                   :password_confirmation, :birth_date)
    end

    def user_edit_params
      params.require(:user).permit(:first_name, :last_name, :email, :birth_date,
                                   :address, :city, :zip_code, :country, :profile_image)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_dashboard_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
    <span class="nav-link">
      <%= breadcrumbs pretext: '<i class="fas fa-folder-open"></i>/ '.html_safe, style: :inline, separator: ' / ', display_single_fragment: true%>
    </span>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="#"><i class="fas fa-search"></i> Search</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href='<%= deposits_path %>'><i class="fas fa-coins"></i> Financial</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" aria-disabled="true"><i class="fas fa-wallet"></i>
          Wallet balance: <%= number_to_currency(current_user.wallet_amount, unit:"R$") %>
        </a>
      </li>
    </ul>
  </div>
</nav>

app/views/users/_user.html.erb
<div class="media text-muted pt-3">
  <% if user.profile_image.attached? %>
    <img alt="" class="mr-2 rounded" style="width: 64px; height: 64px;" src="<%= url_for(user.profile_image) %>" data-holder-rendered="true">
  <% else %>
    <img alt="" class="mr-2 rounded" title="Profile image" style="width: 64px; height: 64px;" src="<%= image_path 'no-photo.jpg' %>" data-holder-rendered="true">
  <% end %>
  <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
    <div class="d-flex justify-content-between align-items-center w-100">
      <strong class="text-primary"><%= user.first_name + " " + user.last_name %></strong>
      <div class="btn-group" role="group" aria-label="userOptions">
        <%= link_to 'View profile', profile_path(user.id), class: 'nav-link' %>
        <%= link_to 'See campaigns', user_campaigns_path(user.id), class: 'nav-link' %>
      </div>
    </div>
    <span class="d-block">Member for <%= distance_of_time_in_words_to_now(user.created_at, :only => [:years, :months]) %></span>
  </div>
</div>

app/views/users/edit.html.erb
<% @title = 'Editing my account - ' %>
<% breadcrumb :user_edit, @user %>
<!-- Form for user editing -->
<div class="container">
  <div class="container-fluid row justify-content-md-center">
    <div class="col-8">
      <%= render 'shared/error_messages', target: @user %>
    </div>
    <div class="card general-card my-3 col-8">
      <div class="card-body">
        <h5 class="card-title text-center">Edit your profile</h5>
        <%= form_for @user do |f| %>
          <div class="general-form">
            <div class="form-label-group">
              <%= f.label :first_name, "First name" %>
              <%= f.text_field :first_name, autofocus: true, class: "form-control", required: true %>
            </div>
            <div class="form-label-group">
              <%= f.label :last_name, "Last name" %>
              <%= f.text_field :last_name, class: "form-control", required: true %>
            </div>
            <div class="form-label-group">
              <%= f.label :email, "Email address" %>
              <%= f.email_field :email, class: "form-control", required: true %>
            </div>
            <div class="form-label-group">
              <%= f.label :birth_date, "Date of birth", class: "w-100" %>
              <%= f.date_select :birth_date, start_year: 1900,
                                end_year: Date.today.year, order: [:day, :month, :year],
                                with_css_classes: true %>
            </div>
            <div class="form-label-group">
              <%= f.label :address, "Full address" %>
              <%= f.text_field :address, class: "form-control", required: false %>
            </div>
            <div class="form-label-group">
              <%= f.label :city, "City" %>
              <%= f.text_field :city, class: "form-control", required: false %>
            </div>
            <div class="form-label-group">
              <%= f.label :zip_code, "Zip Code" %>
              <%= f.text_field :zip_code, class: "form-control", required: false %>
            </div>
            <div class="form-label-group">
              <%= f.label :country, "Country" %>
              <%= f.text_field :country, class: "form-control", required: false %>
            </div>
            <p>
              <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseImageOptions" aria-expanded="false" aria-controls="collapseImageOptions">
                Profile image options
              </button>
            </p>
            <div class="collapse" id="collapseImageOptions">
              <div class="card card-body">
                <div class="form-label-group">
                  <%= f.label :profile_image, "Upload your profile image", class: "w-100" %>
                  <%= f.file_field :profile_image, required: false, accept: 'image/*'%>
                </div>
                <% if @user.profile_image.attached? %>
                  <%= link_to '<i class="fas fa-file-download"></i> Download your current profile image'.html_safe, rails_blob_path(@user.profile_image, disposition: 'attachment'), class: 'nav-link' %>
                  <%= link_to '<i class="fas fa-trash-alt"></i> Delete your current profile image'.html_safe, delete_profile_image_path, method: :delete, class: 'nav-link' %>
                <% end %>
              </div>
            </div>
            <div class="actions">
              <%= f.submit 'Update my profile', class: 'btn btn-primary mt-2' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/home.html.erb
<% @title = 'Featured - ' %>
<% breadcrumb :root %>
<%= render partial: 'shared/options_toolbar' %>
<main role="main" class="container">
  <div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-0">Recent campaigns</h6>
    <%= render @campaigns %>
    <%= paginate @campaigns, param_name: 'campaigns_page' %>
    <small class="d-block text-right mt-3">
      <%= link_to "All campaigns", campaigns_path,
          class: "btn btn-outline-primary" %>
    </small>
  </div>

  <div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-0">Featured users</h6>
    <%= render @users %>
    <%= paginate @users, param_name: 'users_page' %>
    <small class="d-block text-right mt-3">
      <%= link_to "All users", users_path, class: "btn btn-outline-primary" %>
    </small>
  </div>
</main>

app/views/users/index.html.erb
<% @title = 'Users - ' %>
<% breadcrumb :user_index %>
<main role="main" class="container">
  <div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-0">Users</h6>
    <%= render @users %>
    <%= paginate @users %>
    <%= page_entries_info @users %>
  </div>
</main>

app/views/users/new.html.erb
<% @title = 'Creating my account - ' %>
<!-- Form for user registration -->
<div class="container">
  <div class="container-fluid row justify-content-md-center">
    <div class="col-8">
      <%= render 'shared/error_messages', target: @user %>
    </div>
    <div class="card general-card my-3 col-8">
      <div class="card-body">
      <h5 class="card-title text-center">Sign up</h5>
      <%= form_for @user do |f| %>
        <div class="general-form">
          <div class="form-label-group">
            <%= f.label :first_name, "First name" %>
            <%= f.text_field :first_name, autofocus: true, class: "form-control", required: true %>
          </div>
          <div class="form-label-group">
            <%= f.label :last_name, "Last name" %>
            <%= f.text_field :last_name, class: "form-control", required: true %>
          </div>
          <div class="form-label-group">
            <%= f.label :email, "Email address" %>
            <%= f.email_field :email, class: "form-control", required: true %>
          </div>
          <div class="form-label-group">
            <%= f.label :password, "Password" %>
            <%= f.password_field :password, class: "form-control", required: true %>
          </div>
          <div class="form-label-group">
            <%= f.label :password_confirmation, "Password confirmation" %>
            <%= f.password_field :password_confirmation, class: "form-control", required: true %>
          </div>
          <div class="form-label-group">
            <%= f.label :birth_date, "Date of birth", class: "w-100" %>
            <%= f.date_select :birth_date, start_year: 1900,
                end_year: Date.today.year, order: [:day, :month, :year],
                with_css_classes: true %>
          </div>
          <div class="actions">
            <%= f.submit 'Create user', class: 'btn btn-primary mt-2' %>
          </div>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% @title = 'Profile of ' + @user.first_name + ' - ' %>
<% breadcrumb :user, @user %>
<div class="container bootstrap snippet">
  <div class="row">
    <div class="col-sm-10">
      <div class="col-sm-2">
        <% if @user.profile_image.attached? %>
          <a class="pull-left"><img title="Profile image" class="img-fluid rounded-circle align-content-center" src="<%= url_for(@user.profile_image) %>" style="padding-top: 5px"></a>
        <% else %>
          <a class="pull-left"><img title="Profile image" class="img-fluid rounded-circle align-content-center" src="<%= image_path 'no-photo.jpg' %>" style="padding-top: 5px"></a>
        <% end %>
      </div>
      <h1><%= "Profile of " + @user.first_name + " " + @user.last_name %></h1></div>
  </div>
  <div class="row">
    <div class="col-sm-3">
      <!--left col-->

      <ul class="list-group">
        <li class="list-group-item text-muted"><i class="far fa-clock"></i> Activity</li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Joined: </strong></span> <%=  @user.join_date %></li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Last update: </strong></span><%= @user.update_date %> </li>
      </ul>
      <hr class="my-4">
      <ul class="list-group">
        <li class="list-group-item text-muted"><i class="fas fa-chart-line"></i> Stats <i class="fa fa-dashboard fa-1x"></i></li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Campaigns: </strong></span><%= @user.count_campaigns %></li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Contributions: </strong></span><%= @user.count_contributions %></li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Amount received: </strong></span><%= number_to_currency(@user.amount_received, unit:"R$") %></li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Amount donated: </strong></span><%= number_to_currency(@user.amount_contributed, unit:"R$") %></li>
        <% unless current_user.nil? %>
          <% if @user.id == current_user.id %>
            <li class="list-group-item text-right"><span class="pull-left"><strong>Wallet balance: </strong></span><%= number_to_currency(@user.wallet_amount, unit:"R$") %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
    <!--/col-3-->
    <div class="col-sm-9">
      <ul class="list-group">
        <li class="list-group-item text-muted"><i class="far fa-user-circle"></i> Personal Info <i class="fa fa-dashboard fa-1x"></i></li>
        <li class="list-group-item text-left"><span class="pull-left"><strong>Name: </strong></span><%=  @user.first_name + " " + @user.last_name %></li>
        <li class="list-group-item text-left"><span class="pull-left"><strong>Birth Date: </strong></span><%= @user.format_birth_date %></li>
        <li class="list-group-item text-left"><span class="pull-left"><strong>E-mail: </strong></span><%= @user.email %></li>
        <% unless current_user.nil? %>
          <% if @user.id == current_user.id %>
            <li class="list-group-item text-left"><button class="btn btn-outline-primary" href="#">Change your password</button></li>
          <% end %>
        <% end %>
      </ul>
      <hr class="my-4">
      <ul class="list-group">
        <li class="list-group-item text-muted"><i class="fas fa-home"></i> Address <i class="fa fa-dashboard fa-1x"></i></li>
        <li class="list-group-item text-left"><span class="pull-left"><strong>Full Address: </strong></span><%= @user.address %></li>
        <li class="list-group-item text-left"><span class="pull-left"><strong>City: </strong></span><%= @user.city %></li>
        <li class="list-group-item text-left"><span class="pull-left"><strong>Country: </strong></span><%= @user.country %></li>
        <li class="list-group-item text-left"><span class="pull-left"><strong>Zip Code: </strong></span><%= @user.zip_code %></li>
      </ul>
      <% if !current_user.nil? %>
        <% if @user.id == current_user.id %>
          <hr class="my-4">
          <ul class="list-group">
            <li class="list-group-item text-muted"><i class="fas fa-phone"></i> Phones <i class="fa fa-dashboard fa-1x"></i></li>
            <div class="accordion" id="accordionPhones">
              <div class="card">
                <div class="card-header" id="headingView">
                  <h5 class="mb-0">
                    <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseView" aria-expanded="true" aria-controls="collapseView">
                      Your registered phones
                    </button>
                  </h5>
                </div>
                <div id="collapseView" class="collapse" aria-labelledby="headingView" data-parent="#accordionPhones">
                  <div class="card-body">
                    <ul class="list-group">
                      <% unless @user.phones.size == 0 %>
                        <% @user.phones.each do |phone| %>
                          <li class="list-group-item"><span class="pull-left"><strong>Type: </strong></span><%= phone.phone_type %><br><span class="pull-left"><strong>Number: </strong></span><%= phone.number %>
                          <span class='container-fluid'><%= link_to '<i class="fas fa-trash-alt"></i> Delete number'.html_safe, delete_phone_path(phone.id), method: :delete, class: 'btn btn-outline-danger pull-right' %></span>
                          </li>
                        <% end %>
                      <% else %>
                        <li class="list-group-item"><span class="pull-left"><strong>You have no phones registered </strong></span></li>
                      <% end %>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="card">
                <div class="card-header" id="headingAdd">
                  <h5 class="mb-0">
                    <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseAdd" aria-expanded="false" aria-controls="collapseAdd">
                      Add new phone number
                    </button>
                  </h5>
                </div>

                <div id="collapseAdd" class="collapse show" aria-labelledby="headingAdd" data-parent="#accordionPhones">
                  <div class="card-body">
                    <%=form_tag phones_path, method: :post do %>
                      <div class="general-form">
                        <div class="form-label-group">
                          <%= label_tag :phone_type %>
                          <%= select_tag(:phone_type, options_for_select([['Mobile', 'Mobile'], ['Home', 'Home'], ['Commercial', 'Commercial']]))%>
                        </div>
                        <div class="form-label-group">
                          <%= label_tag :number %>
                          <%= number_field_tag :number, nil, class: 'form-control col-5', required: true %>
                        </div>
                        <%= submit_tag 'Add', class: 'btn btn-outline-success'%>
                      </div>
                    <% end %>
                  </div>
                </div>

              </div>
            </div>
          </ul>
          <div class="btn btn-group-toggle">
            <%= link_to 'Edit my profile', edit_profile_path, class: 'btn btn-outline-primary my-4 mr-2' %>
            <%= link_to 'Delete my account', delete_profile_path(@user.id), data: {confirm: 'This action can NOT be undone! All money in your wallet and open campaigns will be lost. Are you sure?'}, :method => :delete, class: 'btn btn-outline-danger my-4 mr-2' %>
          </div>
        <% else %>
          <hr class="my-4">
          <ul class="list-group">
            <li class="list-group-item text-muted"><i class="fas fa-phone"></i> Phones <i class="fa fa-dashboard fa-1x"></i></li>
            <% @user.phones.each do |phone| %>
              <li class="list-group-item text-left"><span class="pull-left"><strong>Type: </strong></span><%= phone.phone_type %><br><span class="pull-left"><strong>Number: </strong></span><%= phone.number %></li>
            <% end %>
          </ul>
        <% end %>
      <% else %>
        <hr class="my-4">
        <ul class="list-group">
          <li class="list-group-item text-muted"><i class="fas fa-phone"></i> Phones <i class="fa fa-dashboard fa-1x"></i></li>
          <% @user.phones.each do |phone| %>
            <li class="list-group-item text-left"><span class="pull-left"><strong>Type: </strong></span><%= phone.phone_type %><br><span class="pull-left"><strong>Number: </strong></span><%= phone.number %></li>
          <% end %>
        </ul>
      <% end %>
    </div>
  </div>
  <!--/col-9-->
</div>
<!--/row-->