config/routes.rb
Rails.application.routes.draw do
  root "application#index"

  resources :campaigns, only:[:index, :create, :update]
  get '/user/:id/campaigns', to: 'campaigns#find_by_user', as: :user_campaigns
  get '/new_campaign', to: 'campaigns#new', as: :new_campaign
  get '/campaign/:id', to: 'campaigns#show', as: :campaign_details
  get '/campaign/:id/edit', to: 'campaigns#edit', as: :edit_campaign
  delete '/campaign/:id/delete_cover_image', to: 'campaigns#delete_cover_image', as: :delete_cover_image

  resources :contributions, only:[:index, :create]

  resources :deposits, only:[:index]

  resources :rewards, only:[:index]

  resources :sessions, only:[:create]
  get '/log_in', to: 'sessions#new', as: :log_in
  delete '/log_out', to: 'sessions#destroy', as: :log_out

  resources :users, only:[:index, :create, :update]
  get '/home', to: 'users#home', as: :home
  get '/profile/:id', to: 'users#show', as: :profile
  delete '/delete_profile', to: 'users#destroy', as: :delete_profile
  get '/sign_up', to: 'users#new', as: :sign_up
  get '/edit_profile', to: 'users#edit', as: :edit_profile
  delete '/delete_profile_image', to: 'users#delete_profile_image', as: :delete_profile_image

  resources :phones, only:[:create]
  delete '/profile/phones/:id/delete', to: 'phones#destroy', as: :delete_phone

  resources :cards, only:[:create, :update]
  get 'payment_methods/cards', to: 'cards#show', as: :payment_methods
  get 'payment_methods/manage', to: 'cards#manage', as: :manage_payment
  delete 'payment_methods/delete_card/:id', to: 'cards#destroy', as: :delete_card
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  has_many :deposits, dependent: :nullify

  validates :card_number, length: {is: 16}
  validates_uniqueness_of :card_number, scope: :user_id,
                          message: "is already registered to your name"

  def get_card_network
    networks = [{pattern: /^4[0-9]{12}(?:[0-9]{3})/, details: {name: "Visa", html: '<i class="fab fa-cc-visa"></i>'}},
                {pattern: /^5[1-5][0-9]{14}/, details: {name: "Mastercard", html: '<i class="fab fa-cc-mastercard"></i>'}},
                {pattern: /^3[47][0-9]{13}/,  details: {name: "Amex", html: '<i class="fab fa-cc-amex"></i>'}},
                {pattern: /^3(?:0[0-5]|[68][0-9])[0-9]{11}/, details: {name: "Diners Club", html: '<i class="fab fa-cc-diners-club"></i>'}},
                {pattern: /^6(?:011|5[0-9]{2})[0-9]{12}/, details: {name: "Discover", html: '<i class="fab fa-cc-discover"></i>'}},
                {pattern: /^(?:2131|1800|35\d{3})\d{11}/, details: {name: "JCB", html: '<i class="fab fa-cc-jcb"></i>'}},
                {pattern: /^((((636368)|(438935)|(504175)|(451416)|(636297))\d{0,10})|((5067)|(4576)|(4011))\d{0,12})$/, details: {name: "Elo", html: '<i class="fas fa-credit-card"></i>'}},
                {pattern: /^(606282\d{10}(\d{3})?)|(3841\d{15})$/, details: {name: "Hipercard", html: '<i class="fas fa-credit-card"></i>'}}]
    networks.each do |network|
        if network[:pattern].match?(self.card_number)
          return network[:details]
        end
    end
    {name: 'Unknown', html: '<i class="fas fa-credit-card"></i>'}
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :require_login

  def manage
    @card = Card.new
    @cards = Card.where(user_id: current_user.id)
  end

  def show
    @cards = Card.where(user_id: current_user.id)
  end

  def create
    @card = Card.new(card_params)
    @card.user = current_user
    begin
      if @card.save
        flash[:success] = [["Completed!", "Payment methods updated"]]
      else
        store_errors_in_flash(@card)
      end
      redirect_to manage_payment_path
    end
  end

  def update
    @card = Card.find(params[:id])
    begin
      if @card.update_attributes(card_params)
        flash[:success] = [['Completed!', 'Payment methods updated']]
      else
        store_errors_in_flash(@card)
      end
      redirect_to manage_payment_path
    end
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy
    flash[:success] = [['Done!', 'Your card has been deleted']]
    redirect_to manage_payment_path
  end

  private

  def card_params
    params.require(:card).permit(:card_number, :card_cvv,
                                 :card_valid_until, :card_owners_name)
  end

end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/manage.html.erb
<% @title = "My payment methods management - " %>
<% breadcrumb :payment_manager %>
<main role="main" class="container">
  <div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-0">Credit/Debit cards</h6>
    <div class="row">
      <% @cards.each do |card| %>
        <% details = card.get_card_network %>
        <div class="col-6 col-sm-4 col-lg-3 mt-3 mb-auto">
          <div class="card h-100 text-center">
            <div class="card-body">
              <h6 class="card-title"><%= (details[:html] + " " + details[:name]).html_safe %></h6>
              <%= form_for card do |f| %>
                <div class="details">
                  <div class="form-label-group">
                    <%= f.label :card_number, "Card number" %>
                    <%= f.number_field :card_number, autofocus: true, class: "form-control", required: true %>
                  </div>
                  <div class="form-label-group">
                    <%= f.label :card_owners_name, "Owner name" %>
                    <%= f.text_field :card_owners_name, class: "form-control", required: true %>
                  </div>
                  <div class="form-label-group">
                    <%= f.label :card_valid_until, "Valid until", class: "w-100" %>
                    <%= f.date_select :card_valid_until, start_year: Date.today.year,
                                      end_year: Date.today.year + 50, order: [:month, :year],
                                      with_css_classes: true %>
                  </div>
                  <div class="form-label-group">
                    <%= f.label :card_cvv, "CVV" %>
                    <%= f.number_field :card_cvv, class: "form-control", required: true %>
                  </div>
                </div>
                </div>
                <div class="card-footer">
                  <div class="actions">
                    <%= f.submit 'Save', class: 'btn btn-outline-success mt-2' %>
                  </div>
                  <%= link_to '<i class="fas fa-trash-alt"></i> Delete'.html_safe, delete_card_path(card.id), method: :delete, data: {confirm: 'This action can NOT be undone. Are you sure?'}, class: "btn btn-outline-danger mt-2" %>
                </div>
              <% end %>
              </div>
        </div>
      <% end %>
      <div class="col-6 col-sm-4 col-lg-3 mt-3 mb-auto">
        <div class="card h-100 text-center">
          <div class="card-body">
            <h6 class="card-title">Add new card</h6>
            <%= form_for @card do |f| %>
              <div class="details">
                <div class="form-label-group">
                  <%= f.label :card_number, "Card number" %>
                  <%= f.number_field :card_number, autofocus: true, class: "form-control", required: true %>
                </div>
                <div class="form-label-group">
                  <%= f.label :card_owners_name, "Owner name" %>
                  <%= f.text_field :card_owners_name, class: "form-control", required: true %>
                </div>
                <div class="form-label-group">
                  <%= f.label :card_valid_until, "Valid until", class: "w-100" %>
                  <%= f.date_select :card_valid_until, start_year: Date.today.year,
                                    end_year: Date.today.year + 50, order: [:month, :year],
                                    with_css_classes: true %>
                </div>
                <div class="form-label-group">
                  <%= f.label :card_cvv, "CVV" %>
                  <%= f.number_field :card_cvv, class: "form-control", required: true %>
                </div>
              </div>
              </div>
              <div class="card-footer">
                <div class="actions">
                  <%= f.submit 'Save', class: 'btn btn-outline-success mt-2' %>
                </div>
              </div>
            <% end %>
            </div>
      </div>
    </div>
    <%= link_to 'Done', payment_methods_path, class: "btn btn-outline-primary mt-3" %>
  </div>
</main>

app/views/cards/show.html.erb
<% @title = "My payment methods - " %>
<% breadcrumb :payment %>
<main role="main" class="container">
  <div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-0">Credit/Debit cards</h6>
    <div class="row">
      <% @cards.each do |card| %>
        <% details = card.get_card_network %>
        <div class="col-6 col-sm-4 col-lg-3 mt-3 mb-auto">
          <div class="card h-100 text-center">
            <div class="card-body">
              <h6 class="card-title"><%= (details[:html] + " " + details[:name]).html_safe %></h6>
              <div class="details">
                <ul class="list-group">
                  <li class="list-group-item">Card Number<br><%= "**** **** **** " + card.card_number[12..16] %></li>
                  <li class="list-group-item">Valid until<br><%= card.card_valid_until.month.to_s + "/" + card.card_valid_until.year.to_s %></li>
                  <li class="list-group-item">Owner name<br><%= card.card_owners_name %></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <%= link_to '<i class="fas fa-toolbox"></i> Manage'.html_safe, manage_payment_path, class: "btn btn-outline-primary mt-3" %>
  </div>
</main>