config/routes.rb
Rails.application.routes.draw do
  root "application#index"

  resources :campaigns, only:[:index, :create, :update]
  get '/user/:id/campaigns', to: 'campaigns#find_by_user', as: :user_campaigns
  get '/new_campaign', to: 'campaigns#new', as: :new_campaign
  get '/campaign/:id', to: 'campaigns#show', as: :campaign_details
  get '/campaign/:id/edit', to: 'campaigns#edit', as: :edit_campaign
  delete '/campaign/:id/delete_cover_image', to: 'campaigns#delete_cover_image', as: :delete_cover_image

  resources :contributions, only:[:index, :create]

  resources :deposits, only:[:index]

  resources :rewards, only:[:index]

  resources :sessions, only:[:create]
  get '/log_in', to: 'sessions#new', as: :log_in
  delete '/log_out', to: 'sessions#destroy', as: :log_out

  resources :users, only:[:index, :create, :update]
  get '/home', to: 'users#home', as: :home
  get '/profile/:id', to: 'users#show', as: :profile
  delete '/delete_profile', to: 'users#destroy', as: :delete_profile
  get '/sign_up', to: 'users#new', as: :sign_up
  get '/edit_profile', to: 'users#edit', as: :edit_profile
  delete '/delete_profile_image', to: 'users#delete_profile_image', as: :delete_profile_image

  resources :phones, only:[:create]
  delete '/profile/phones/:id/delete', to: 'phones#destroy', as: :delete_phone

  resources :cards, only:[:create, :update]
  get 'payment_methods/cards', to: 'cards#show', as: :payment_methods
  get 'payment_methods/manage', to: 'cards#manage', as: :manage_payment
  delete 'payment_methods/delete_card/:id', to: 'cards#destroy', as: :delete_card
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  # Cover image via ActiveStorage
  has_one_attached :cover_image

  belongs_to :user, optional: true
  has_many :contributions, dependent: :delete_all
  has_many :rewards, dependent: :delete_all

  def count_contributors
    self.contributions.size
  end

  def funding_percentage
    (100 * self.current_amount/self.desired_amount).round(2)
  end

end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  before_action :require_login, except: [:index, :find_by_user, :show]

  def index
    @campaigns = Campaign.all.page(params[:page])
  end

  def edit
    @campaign = Campaign.find_by(id: params[:id])

    if @campaign.user_id != current_user.id
      flash[:danger] = [["Oh, no!", "You cannot edit this campaign!"]]
      redirect_to campaign_details_path(@campaign.id)
    end
  end

  def update
    @campaign = Campaign.find_by(id: params[:id])

    if @campaign.user_id != current_user.id
      flash[:danger] = [["Oh, no!", "You cannot edit this campaign!"]]
      redirect_to campaign_details_path(@campaign.id)
    end

    unless params[:cover_image].nil?
      @campaign.cover_image.destroy
      @campaign.cover_image.attach(params[:cover_image])
    end

    if @campaign.update_attributes(campaign_edit_params)
      flash[:success] = [["Alright!", "Your campaign was updated"]]
      redirect_to campaign_details_path(@campaign.id)
    else
      render 'edit'
    end
  end

  def delete_cover_image
    @campaign = Campaign.find_by(id: params[:id], user_id: current_user.id)
    @campaign.cover_image.destroy
    flash[:success] = [['All good!', 'Campaign cover image has been deleted']]
    redirect_to edit_campaign_path
  end

  def create
    @campaign = Campaign.new(campaign_creation_params)
    @campaign.current_amount = 0          # All campaigns start at 0 dollars.
    @campaign.user_id = current_user.id   # The current user is the creator.

    if @campaign.save
      flash.clear
      flash[:success] = [["", "Campaign successfully created!"]]
      redirect_to campaigns_path
    else
      render 'new'
    end
  end

  def find_by_user
    @user = User.find(params[:id])
    @campaigns = Campaign.where(:user_id => params[:id]).page(params[:page])
  end

  def new
    @campaign = Campaign.new
  end

  def show
    @campaign = Campaign.find(params[:id])
    @creator = User.find(@campaign.user_id) unless @campaign.user_id.nil?
    unless current_user.nil?
      @contribution = Contribution.where(campaign_id: @campaign.id,
                                         user_id: current_user.id).first
      @user_rewards = current_user.rewards
    end
    @contribution = Contribution.new if @contribution.nil?
    @user_rewards = [] if @user_rewards.nil?
  end

  private
    def campaign_creation_params
      params.require(:campaign).permit(:title, :description, :desired_amount)
    end

    def campaign_edit_params
      params.require(:campaign).permit(:title, :description, :cover_image)
    end

end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/views/campaigns/_campaign.html.erb
<div class="media text-muted pt-3">
  <% if campaign.cover_image.attached? %>
    <img alt="" class="mr-2 rounded" style="width: 64px; height: 64px;" src="<%= url_for(campaign.cover_image) %>" data-holder-rendered="true">
  <% else %>
    <img alt="" class="mr-2 rounded" style="width: 64px; height: 64px;" src="<%= image_path 'no-cover.png' %>" data-holder-rendered="true">
  <% end %>
  <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
    <div class="d-flex justify-content-between align-items-center w-100">
      <strong class="text-primary"><%= campaign.title %></strong>
      <%= link_to "View Details", campaign_details_path(campaign) %>
    </div>
    <span class="d-block"><%= campaign.description %></span>
    <strong class="text-secondary">Progress: <%= ((campaign.current_amount/campaign.desired_amount)*100).round(2) %>%</strong>
  </div>
</div>

app/views/campaigns/edit.html.erb
<% @title = "Editing your campaign - " %>
<% breadcrumb :campaign_edit, @campaign %>
<!-- Form for campaign creation -->
<div class="container">
  <div class="container-fluid row justify-content-md-center">
    <div class="col-8">
      <%= render 'shared/error_messages', target: @campaign %>
    </div>
    <div class="card general-card my-3 col-8">
      <div class="card-body">
        <h5 class="card-title text-center">Edit your campaign</h5>
        <%= form_for @campaign do |f| %>
          <div class="general-form">
            <div class="form-label-group">
              <%= f.label :title, "Campaign name" %>
              <%= f.text_field :title, autofocus: true, class: "form-control", required: true %>
            </div>
            <div class="form-label-group">
              <%= f.label :description, "Campaign description" %>
              <%= f.text_area :description, rows: 4, class: "form-control", required: true %>
            </div>
            <button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#collapseImageOptions" aria-expanded="false" aria-controls="collapseImageOptions">
              Cover image options
            </button>
            <div class="collapse mt-3" id="collapseImageOptions">
              <div class="card card-body">
                <div class="form-label-group">
                  <%= f.label :cover_image, "Upload your campaign cover image", class: "w-100" %>
                  <%= f.file_field :cover_image, required: false, accept: 'image/*'%>
                </div>
                <% if @campaign.cover_image.attached? %>
                  <%= link_to '<i class="fas fa-file-download"></i> Download current cover image'.html_safe, rails_blob_path(@campaign.cover_image, disposition: 'attachment'), class: 'nav-link' %>
                  <%= link_to '<i class="fas fa-trash-alt"></i> Delete current cover image'.html_safe, delete_cover_image_path(@campaign.id), method: :delete, class: 'nav-link' %>
                <% end %>
              </div>
            </div>
            <div class="actions mt-2">
              <%= f.submit 'Update', class: 'btn btn-primary mt-2' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/campaigns/find_by_user.html.erb
<% @title = "Campaigns of " + @user.first_name + " - " %>
<% breadcrumb :user_campaigns, @user %>
<%= render partial: 'shared/options_toolbar' %>
<main role="main" class="container">
  <div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-0"><%= "Campaigns of " + @user.first_name %></h6>
    <%= render @campaigns %>
    <%= paginate @campaigns %>
    <%= page_entries_info @campaigns %>
  </div>
</main>

app/views/campaigns/index.html.erb
<% @title = "Campaigns - " %>
<% breadcrumb :campaigns_index %>
<main role="main" class="container">
  <div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-0">All campaigns</h6>
    <%= render @campaigns %>
    <%= paginate @campaigns %>
    <%= page_entries_info @campaigns %>
  </div>
</main>

app/views/campaigns/new.html.erb
<% @title = "Starting a new campaign - " %>
<% breadcrumb :campaign_new %>
<!-- Form for campaign creation -->
<div class="container">
  <div class="container-fluid row justify-content-md-center">
    <div class="col-8">
      <%= render 'shared/error_messages', target: @campaign %>
    </div>
    <div class="card general-card my-3 col-8">
      <div class="card-body">
      <h5 class="card-title text-center">Create a campaign</h5>
      <%= form_for @campaign do |f| %>
        <div class="general-form">
          <div class="form-label-group">
            <%= f.label :title, "Campaign name" %>
            <%= f.text_field :title, autofocus: true, class: "form-control", required: true %>
          </div>
          <div class="form-label-group">
            <%= f.label :description, "Campaign description" %>
            <%= f.text_area :description, rows: 4, class: "form-control", required: true %>
          </div>
          <div class="form-label-group">
            <%= f.label :desired_amount,
                "Desired campaign amount (Cannot be altered!)" %>
            <%= f.number_field :desired_amount, in: 0.99..1000000.00,
                step: 0.01, precison: 2, class: "form-control col-3",
                required: true %>
          </div>
          <div class="actions">
            <%= f.submit 'Create campaign', class: 'btn btn-primary mt-2' %>
          </div>
        </div>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/campaigns/show.html.erb
<% @title = @campaign.title + " - "%>
<% breadcrumb :campaign, @campaign %>
<!-- Campaign page -->
<div class="container bootstrap snippet">
  <% unless current_user.nil? %>
    <% if current_user.id == @campaign.user_id %>
      <div class="row my-3">
        <div class="col text-left align-self-center">
          <h5 class="mx-2 my-0">Manage my campaign</h5>
        </div>
        <div class="col text-right">
          <%= link_to 'Edit campaign', edit_campaign_path,
              class: 'btn btn-primary mx-2' %>
        </div>
      </div>
      <hr class="my-2">
    <% end %>
  <% end %>
  <div class="row my-4">
    <div class="col text-center">
      <h2><%= @campaign.title %></h2>
    </div>
  </div>
  <div class="row my-4">
    <div class="col text-center">
      <% if @campaign.cover_image.attached? %>
        <img title="Cover image" class="img-fluid mx-auto d-block rounded" src="<%= url_for(@campaign.cover_image) %>">
      <% else %>
        <img title="Cover image" class="img-fluid mx-auto d-block rounded" src="<%= image_path 'no-cover.png' %>">
      <% end %>
    </div>
  </div>
  <hr class="my-4">
  <div class="row">
    <div class="col text-center">
      <h4 class="mb-3">Campaign status</h4>
      <% if @campaign.funding_percentage < 100 %>
        <div class="progress" style="height: 8px;">
          <div class="progress-bar bg-success" role="progressbar"
               style="width: <%= @campaign.funding_percentage %>%"
               aria-valuenow="<%= @campaign.funding_percentage %>"
               aria-valuemin="0"
               aria-valuemax="100">
          </div>
        </div>
        <h6 class="mt-2">
          This campaign is <%= @campaign.funding_percentage %>% funded!
          Help us make it to 100%!
        </h6>
      <% else %>
        <div class="progress" style="height: 8px;">
          <div class="progress-bar bg-success" role="progressbar"
               style="width: 100%" aria-valuenow="100" aria-valuemin="0"
               aria-valuemax="100">
          </div>
        </div>
        <h6 class="mt-2">
          This campaign was successfully funded!
          But you can still help us reach our extra goals!
        </h6>
      <% end %>
    </div>
  </div>
  <% unless current_user.nil? %>
    <hr class="my-4">
    <div class="row">
      <div class="col text-center">
        <h4>Campaign contribution</h4>
        <% if @contribution.value.nil? %>
          <div class="card general-card mx-auto my-2 col-8">
            <div class="card-body">
              <h5 class="card-title text-center">Contribute to this campaign</h5>
              <%= render 'shared/error_messages', target: @contribution %>
              <%= form_for @contribution do |f| %>
                <div class="general-form text-center">
                  <div class="form-label-group">
                    <%= f.hidden_field :campaign_id, value: @campaign.id %>
                    <%= f.label :value, "Contribution ammount (R$)" %>
                    <%= f.number_field :value, in: 0.01..1000000.00, step: 0.01,
                        precison: 2,
                        class: "form-control text-justify col-3 mx-auto",
                        required: true %>
                  </div>
                  <div class="actions">
                    <%= f.submit 'Contribute',
                        class: 'btn btn-outline-success mt-3 w-75' %>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        <% else %>
          <h6>
            You have a contribution to this campaign in the value of:
            <div class="text-success">
              <%= number_to_currency(@contribution.value, unit:"R$") %>
            </div>
            Thank you for participating!
          </h6>
        <% end %>
      </div>
    </div>
  <% end %>
  <hr class="my-4">
  <div class="row">
    <div class="col text-center">
      <h4 class="mb-4">Campaign details</h4>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8">
      <ul class="list-group">
        <li class="list-group-item text-muted">
          <i class="fas fa-scroll"></i>
          Description
        </li>
        <li class="list-group-item">
          <div class="campaign-description"> <%= @campaign.description %> </div>
        </li>
      </ul>
    </div>
    <div class="col-sm-4">
      <ul class="list-group">
        <li class="list-group-item text-muted">
          <i class="fas fa-chart-line"></i> Statistics
        </li>
        <li class="list-group-item">
          <strong> Desired amount: </strong>
          <%= number_to_currency(@campaign.desired_amount, unit:"R$") %>
        </li>
        <li class="list-group-item">
          <strong> Amount received: </strong>
          <%= number_to_currency(@campaign.current_amount, unit:"R$") %>
        </li>
        <li class="list-group-item">
          <strong> Number of contributions: </strong>
          <%= @campaign.count_contributors %>
        </li>
        <li class="list-group-item">
          <strong> Time remaining: </strong>
          <%= distance_of_time_in_words(Time.now,
              @campaign.created_at + 60.days, only: [:days, :hours],
              accumulate_on: :days) %>
        </li>
      </ul>
      <hr class="my-4">
      <ul class="list-group">
        <li class="list-group-item text-muted">
          <i class="fas fa-user"></i> Creator information
        </li>
        <% unless @creator.nil? %>
          <li class="list-group-item">
            <strong> Name: </strong>
            <%= @creator.first_name + " " + @creator.last_name %>
          </li>
          <li class="list-group-item">
            <strong> E-mail: </strong>
            <%= @creator.email %>
          </li>
          <li class="list-group-item">
            <strong> Campaigns created: </strong>
            <%= @creator.count_campaigns %>
          </li>
          <%= link_to "More information", profile_path(@creator),
              class: "btn btn-outline-primary mt-3" %>
      <% else %>
          <li class="list-group-item">
            <strong> The creator of this campaign deleted his account! </strong>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <hr class="my-4">
  <div class="row">
    <div class="col text-center">
      <h4 class="mb-4">Campaign rewards</h4>
    </div>
  </div>
  <div class="row">
    <% @campaign.rewards.order(:min_value).each do |reward| %>
      <% user_has_reward = @user_rewards.include?(reward) %>
      <% reward_border = user_has_reward ? "border-success" : "" %>
      <div class="col-6 col-sm-4 col-lg-3 mb-4">
        <div class="card <%= reward_border %> h-100 text-center">
          <div class="card-header bg-transparent">
            <%= image_tag 'no-cover.png', class: "card-img-top" %>
          </div>
          <div class="card-body px-2">
            <h6 class="card-title"><%= reward.name %></h6>
            <div class="reward-description">
            A simple description of the reward. It must be about 3 sentences
            long to stay inside the card. It must offer an accurate description!
            </div>
          </div>
          <div class="card-footer">
            <% if user_has_reward %>
              <div class="btn btn-success btn-no-pointer-events mb-3 w-100">
                Reward acquired!
              </div>
            <% else %>
              <%= link_to "I want this!", '#',
                  class: "btn btn-outline-primary mb-3 w-100" %>
            <% end %>
            Minimum donation of:
            <%= number_to_currency(reward.min_value, unit:"R$") %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>