config/routes.rb
Rails.application.routes.draw do
  root "application#index"

  resources :campaigns, only:[:index, :create, :update]
  get '/user/:id/campaigns', to: 'campaigns#find_by_user', as: :user_campaigns
  get '/new_campaign', to: 'campaigns#new', as: :new_campaign
  get '/campaign/:id', to: 'campaigns#show', as: :campaign_details
  get '/campaign/:id/edit', to: 'campaigns#edit', as: :edit_campaign
  delete '/campaign/:id/delete_cover_image', to: 'campaigns#delete_cover_image', as: :delete_cover_image

  resources :contributions, only:[:index, :create]

  resources :deposits, only:[:index]

  resources :rewards, only:[:index]

  resources :sessions, only:[:create]
  get '/log_in', to: 'sessions#new', as: :log_in
  delete '/log_out', to: 'sessions#destroy', as: :log_out

  resources :users, only:[:index, :create, :update]
  get '/home', to: 'users#home', as: :home
  get '/profile/:id', to: 'users#show', as: :profile
  delete '/delete_profile', to: 'users#destroy', as: :delete_profile
  get '/sign_up', to: 'users#new', as: :sign_up
  get '/edit_profile', to: 'users#edit', as: :edit_profile
  delete '/delete_profile_image', to: 'users#delete_profile_image', as: :delete_profile_image

  resources :phones, only:[:create]
  delete '/profile/phones/:id/delete', to: 'phones#destroy', as: :delete_phone

  resources :cards, only:[:create, :update]
  get 'payment_methods/cards', to: 'cards#show', as: :payment_methods
  get 'payment_methods/manage', to: 'cards#manage', as: :manage_payment
  delete 'payment_methods/delete_card/:id', to: 'cards#destroy', as: :delete_card
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/campaign.rb
class Campaign < ApplicationRecord
  # Cover image via ActiveStorage
  has_one_attached :cover_image

  belongs_to :user, optional: true
  has_many :contributions, dependent: :delete_all
  has_many :rewards, dependent: :delete_all

  def count_contributors
    self.contributions.size
  end

  def funding_percentage
    (100 * self.current_amount/self.desired_amount).round(2)
  end

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  has_many :deposits, dependent: :nullify

  validates :card_number, length: {is: 16}
  validates_uniqueness_of :card_number, scope: :user_id,
                          message: "is already registered to your name"

  def get_card_network
    networks = [{pattern: /^4[0-9]{12}(?:[0-9]{3})/, details: {name: "Visa", html: '<i class="fab fa-cc-visa"></i>'}},
                {pattern: /^5[1-5][0-9]{14}/, details: {name: "Mastercard", html: '<i class="fab fa-cc-mastercard"></i>'}},
                {pattern: /^3[47][0-9]{13}/,  details: {name: "Amex", html: '<i class="fab fa-cc-amex"></i>'}},
                {pattern: /^3(?:0[0-5]|[68][0-9])[0-9]{11}/, details: {name: "Diners Club", html: '<i class="fab fa-cc-diners-club"></i>'}},
                {pattern: /^6(?:011|5[0-9]{2})[0-9]{12}/, details: {name: "Discover", html: '<i class="fab fa-cc-discover"></i>'}},
                {pattern: /^(?:2131|1800|35\d{3})\d{11}/, details: {name: "JCB", html: '<i class="fab fa-cc-jcb"></i>'}},
                {pattern: /^((((636368)|(438935)|(504175)|(451416)|(636297))\d{0,10})|((5067)|(4576)|(4011))\d{0,12})$/, details: {name: "Elo", html: '<i class="fas fa-credit-card"></i>'}},
                {pattern: /^(606282\d{10}(\d{3})?)|(3841\d{15})$/, details: {name: "Hipercard", html: '<i class="fas fa-credit-card"></i>'}}]
    networks.each do |network|
        if network[:pattern].match?(self.card_number)
          return network[:details]
        end
    end
    {name: 'Unknown', html: '<i class="fas fa-credit-card"></i>'}
  end
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  validates :campaign_id, presence: true

  belongs_to :user, optional: true
  belongs_to :campaign
end

app/models/deposit.rb
class Deposit < ApplicationRecord
  belongs_to :card, optional: true
  belongs_to :payment_method
  belongs_to :transaction_state
  belongs_to :user
end

app/models/payment_method.rb
class PaymentMethod < ApplicationRecord
  has_many :deposits
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :user
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :campaign
  has_and_belongs_to_many :users, dependent: :delete_all
end

app/models/transaction_state.rb
class TransactionState < ApplicationRecord
  has_many :contributions
  has_many :deposits
end

app/models/user.rb
class User < ApplicationRecord
  # Profile image via ActiveStorage
  has_one_attached :profile_image

  # Sorcery gem:
  authenticates_with_sorcery!
  attr_accessor :skip_password

  # Validation:
  validates :password, length: {minimum: 8},
            if: -> {new_record? || changes[:crypted_password]},
            unless: :skip_password
  validates :password, confirmation: true,
            if: -> {new_record? || changes[:crypted_password]}
  validates :password_confirmation, presence: true,
            if: -> {new_record? || changes[:crypted_password]}
  validates :email, uniqueness: true


  # Relationships:
  belongs_to :user_role
  has_and_belongs_to_many :rewards, dependent: :delete_all
  has_many :cards, dependent: :delete_all
  has_many :campaigns
  has_many :contributions
  has_many :deposits, dependent: :delete_all
  has_many :phones, dependent: :delete_all

  # Methods:
  def amount_contributed
    amount = 0.00
    self.contributions.each do |donation|
      amount += donation.value
    end
    amount
  end

  def amount_received
    amount = 0.00
    self.campaigns.each do |campaign|
      amount += campaign.current_amount
    end
    amount
  end

  def count_contributions
    self.contributions.size
  end

  def count_campaigns
    self.campaigns.size
  end

  def join_date
    day = self.created_at.day.to_s
    mount = self.created_at.month.to_s
    year = self.created_at.year.to_s
    "#{day}/#{mount}/#{year}"
  end

  def update_date
    day = self.updated_at.day.to_s
    mount = self.updated_at.month.to_s
    year = self.updated_at.year.to_s
    "#{day}/#{mount}/#{year}"
  end

  def format_birth_date
    day = self.birth_date.day.to_s
    mount = self.birth_date.month.to_s
    year = self.birth_date.year.to_s
    "#{day}/#{mount}/#{year}"
  end

end

app/models/user_role.rb
class UserRole < ApplicationRecord
  has_many :users
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :require_login

  def manage
    @card = Card.new
    @cards = Card.where(user_id: current_user.id)
  end

  def show
    @cards = Card.where(user_id: current_user.id)
  end

  def create
    @card = Card.new(card_params)
    @card.user = current_user
    begin
      if @card.save
        flash[:success] = [["Completed!", "Payment methods updated"]]
      else
        store_errors_in_flash(@card)
      end
      redirect_to manage_payment_path
    end
  end

  def update
    @card = Card.find(params[:id])
    begin
      if @card.update_attributes(card_params)
        flash[:success] = [['Completed!', 'Payment methods updated']]
      else
        store_errors_in_flash(@card)
      end
      redirect_to manage_payment_path
    end
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy
    flash[:success] = [['Done!', 'Your card has been deleted']]
    redirect_to manage_payment_path
  end

  private

  def card_params
    params.require(:card).permit(:card_number, :card_cvv,
                                 :card_valid_until, :card_owners_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= (@title.nil?? '':@title) + 'KoopaFundMe'%></title>
    <%= favicon_link_tag asset_path('icon64.png'), :rel => 'icon', :type =>  'image/png' %>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/simple-line-icons/2.4.1/css/simple-line-icons.css">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--Navigation bar-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light static-top">
      <div class="container">
      <a class="navbar-brand" href="<%= root_path %>">
        <img class="img-fluid rounded" src='<%= image_path 'icon32.png' %>' alt="">
        KoopaFundMe
      </a>
      <% unless current_user.nil? %>
        <ul class="nav navbar-nav mr">
          <li class="nav-item">
            <%= link_to 'Start Campaign', new_campaign_path, class: 'btn btn-success' %>
          </li>
          <li class="nav-item dropdown mx-2">
            <a class="nav-link dropdown-toggle" id="profileDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user-alt"></i> <%= current_user.first_name %></a>
            <div class="dropdown-menu" aria-labelledby="profileDropdown">
              <%= link_to '<i class="fas fa-columns"></i> Dashboard'.html_safe, home_path, class: "dropdown-item"%>
              <%= link_to '<i class="fas fa-user-edit"></i> Profile'.html_safe, profile_path(current_user.id), class: "dropdown-item"%>
              <%= link_to '<i class="fas fa-flag-checkered"></i> My Campaigns'.html_safe, user_campaigns_path(current_user.id), class: "dropdown-item"%>
              <%= link_to '<i class="fas fa-hand-holding-usd"></i> My Contributions'.html_safe, contributions_path, class: 'dropdown-item'%>
              <%= link_to '<i class="fas fa-trophy"></i> My Rewards'.html_safe, rewards_path, class: 'dropdown-item'%>
              <%= link_to '<i class="fas fa-credit-card"></i> Payment methods'.html_safe, payment_methods_path, class: 'dropdown-item'%>
              <%= link_to '<i class="fas fa-sign-out-alt"></i> Log out'.html_safe, log_out_path, method: :delete, class: 'dropdown-item'%>
            </div>
          </li>
        </ul>
      <% else %>
        <div class="btn btn-group-toggle">
          <%= link_to 'Log In', log_in_path, class: 'btn btn-primary' %>
          <%= link_to 'Sign up', sign_up_path, class: 'btn btn-primary' %>
        </div>
      <% end %>
      </div>
    </nav>

    <!-- User dashboard -->
    <% if current_user.nil?%>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="navbar-collapse offcanvas-collapse" id="navbarsExampleDefault">
          <span class="nav-link">
            <%= breadcrumbs pretext: '<i class="fas fa-folder-open"></i>/ '.html_safe, style: :inline, separator: ' / ' %>
          </span>
        </div>
      </nav>
    <% else %>
     <%= render partial: 'users/dashboard_header' %>
    <% end %>

    <!--Notifications-->
    <div class="content-page">
      <% [:success, :info, :warning, :danger].each do |state| %>
        <% unless flash[state].nil? %>
          <% flash[state].each do |message| %>
            <div class="alert alert-<%= state %> alert-dismissible text-center" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <strong><%= message[0] %></strong> <%= message[1] %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>

    <!-- Yield to render page -->
    <%= yield %>

    <!-- Footer -->
    <footer class="footer bg-light">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 h-100 text-center text-lg-left my-auto">
            <ul class="list-inline mb-2">
              <li class="list-inline-item">
                <a href="#">About</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Contact</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Terms of Use</a>
              </li>
              <li class="list-inline-item">&sdot;</li>
              <li class="list-inline-item">
                <a href="#">Privacy Policy</a>
              </li>
            </ul>
            <p class="text-muted small mb-4 mb-lg-0">&copy; KoopaFundMe 2018. All Rights Reserved.</p>
          </div>
          <div class="col-lg-6 h-100 text-center text-lg-right my-auto">
            <ul class="list-inline mb-0">
              <li class="list-inline-item mr-3">
                <a href="https://www.facebook.com/StructUnB">
                  <i class="fab fa-facebook fa-2x fa-fw"></i>
                </a>
              </li>
              <li class="list-inline-item mr-3">
                <a href="https://www.instagram.com/structunb">
                  <i class="fab fa-instagram fa-2x fa-fw"></i>
                </a>
              </li>
              <li class="list-inline-item mr-3">
                <a href="https://gitlab.com/AndreLaranjeira/koopafundme">
                  <i class="fab fa-gitlab fa-2x fa-fw"></i>
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
    </body>
</html>

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
  <div class="error_explanation">
    <% target.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger" role="alert">
        <%= msg + "!" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_options_toolbar.html.erb
<div class="nav-scroller bg-white shadow-sm text-center">
  <nav class="nav nav-underline text-center justify-content-center">
    <li class="nav-text text-primary mx-4">Order by:
      <div class="input-group mb-3">
        <select class="custom-select" id="inputOrderBy">
          <option selected>Choose...</option>
          <option value="1">Most Recent</option>
          <option value="2">Title</option>
          <option value="3">Progress</option>
        </select>
        <div class="input-group-append">
          <button class="btn btn-outline-primary" type="button">Refresh</button>
        </div>
      </div>
    </li>
    <li class="nav-text text-primary mx-4">Show only:
      <div class="btn-group-toggle" data-toggle="buttons">
        <label class="btn btn-outline-primary active">
          <input type="checkbox" checked autocomplete="off"> Campaigns
        </label>
        <label class="btn btn-outline-primary active">
          <input type="checkbox" checked autocomplete="off"> Users
        </label>
        <label class="btn btn-outline-primary active">
          <input type="checkbox" checked autocomplete="off"> Recent
        </label>
      </div>
    </li>
  </nav>
</div>